on:
  push:
    branches: [main]
  pull_request:
name: CI # Continuous Integration

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - run: cargo test --workspace --all-targets

  test-features-reqwest-middleware:
    name: Run test suite for `reqwest-middleware` with every feature combination
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@896b264186645b15ca5257f34d9f700946916f88 # cargo-hack
      - name: test
        run: cargo hack test --feature-powerset -p astral-reqwest-middleware
  check-wasm32-reqwest-middleware:
    name: Run `cargo check` for `reqwest-middleware` on `wasm32-unknown-unknown`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo build --target wasm32-unknown-unknown -p astral-reqwest-middleware --all-features
  test-features-retry:
    name: Run test suite for `reqwest-retry` with every feature combination
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@896b264186645b15ca5257f34d9f700946916f88 # cargo-hack
      - name: test
        run: cargo hack test --feature-powerset -p astral-reqwest-retry
  test-features-reqwest-tracing:
    name: Run test suite for `reqwest-tracing` with every feature combination
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@896b264186645b15ca5257f34d9f700946916f88 # cargo-hack
      # Old opentelemetry features group to improve performance
      - name: test
        run: cargo hack test --feature-powerset -p astral-reqwest-tracing --exclude-features opentelemetry_0_20 --group-features opentelemetry_0_21,opentelemetry_0_22,opentelemetry_0_23,opentelemetry_0_24,opentelemetry_0_25,opentelemetry_0_26,opentelemetry_0_27
        env:
          CARGO_PROFILE_DEV_DEBUG: "line-tables-only"

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Clippy check
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  clippy-features:
    name: Run clippy for every feature combination
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@896b264186645b15ca5257f34d9f700946916f88 # cargo-hack
      - name: test
        run: cargo hack clippy --feature-powerset

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Check spelling
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # master

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --all-features --workspace

  publish-check:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      - run: cargo publish --workspace --dry-run --keep-going
